# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Chelsey and Gully Wedding
email: chuglywed@gmail.com
author: Chelsey Contillo and Michael Gully-Santiago
description: > # "Homepage for Chelsey Contillo and Michael Gully-Santiago
 wedding in Austin Texas on October 28, 2017.  
copyright: 'Copyright &copy; 2017 Chelsey and Gully. All Rights Reserved.'
credits: 'Credits: forked from Shane Weng.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    text: Blog
    url: http://chugly.github.io/
  - title: instagram
    text: Photos
    url: https://www.instagram.com/explore/tags/chuglywed/
  - title: spotify
    text: Playlist
    url: https://open.spotify.com/user/126045799/playlist/1KnnWPmEOm3PiQ93mpAQuF
